export const courses = [
  {
    title: 'Introduction to Digital Marketing',
    author: 'Emily Johnson',
    price: 45,
    category: 'marketing',
    image: '.\\images\\01.jpg',
  },
  {
    title: 'Agile Project Management',
    author: 'Michael Smith',
    price: 60,
    category: 'management',
    image: '.\\images\\02.jpg',
  },
  {
    title: 'Effective Interviewing Techniques',
    author: 'Sarah Connor',
    price: 30,
    category: 'hr-recruiting',
    image: '.\\images\\03.jpg',
  },
  {
    title: 'UI/UX Fundamentals',
    author: 'David Lee',
    price: 55,
    category: 'design',
    image: '.\\images\\04.jpg',
  },
  {
    title: 'Python for Beginners',
    author: 'Jessica Alba',
    price: 75,
    category: 'development',
    image: '.\\images\\05.jpg',
  },
  {
    title: 'Content Marketing Strategy',
    author: 'Chris Evans',
    price: 40,
    category: 'marketing',
    image: '.\\images\\06.jpg',
  },
  {
    title: 'Leadership Skills for New Managers',
    author: 'Laura Martinez',
    price: 65,
    category: 'management',
    image: '.\\images\\07.jpg',
  },
  {
    title: 'Onboarding New Employees',
    author: 'James Rodriguez',
    price: 25,
    category: 'hr-recruiting',
    image: '.\\images\\08.jpg',
  },
  {
    title: 'Graphic Design Principles',
    author: 'Nicole Brown',
    price: 50,
    category: 'design',
    image: '.\\images\\09.jpg',
  },
  {
    title: 'JavaScript from Scratch',
    author: 'Robert Downey',
    price: 80,
    category: 'development',
    image: '.\\images\\10.jpg',
  },
  {
    title: 'Social Media Marketing',
    author: 'Amanda Green',
    price: 35,
    category: 'marketing',
    image: '.\\images\\11.jpg',
  },
  {
    title: 'Scrum Master Certification Prep',
    author: 'Daniel White',
    price: 70,
    category: 'management',
    image: '.\\images\\12.jpg',
  },
  {
    title: 'Conflict Resolution in the Workplace',
    author: 'Olivia Black',
    price: 45,
    category: 'hr-recruiting',
    image: '.\\images\\13.jpg',
  },
  {
    title: 'Wireframing and Prototyping',
    author: 'Ethan Miller',
    price: 55,
    category: 'design',
    image: '.\\images\\14.jpg',
  },
  {
    title: 'Web Development Bootcamp',
    author: 'Sophia Wilson',
    price: 120,
    category: 'development',
    image: '.\\images\\15.jpg',
  },
  {
    title: 'SEO Essentials',
    author: 'Liam Moore',
    price: 30,
    category: 'marketing',
    image: '.\\images\\16.jpg',
  },
  {
    title: 'Financial Management for Non-Managers',
    author: 'Ava Taylor',
    price: 50,
    category: 'management',
    image: '.\\images\\17.jpg',
  },
  {
    title: 'Diversity and Inclusion Training',
    author: 'Noah Anderson',
    price: 20,
    category: 'hr-recruiting',
    image: '.\\images\\18.jpg',
  },
  {
    title: 'Typography Masterclass',
    author: 'Charlotte Thomas',
    price: 60,
    category: 'design',
    image: '.\\images\\19.jpg',
  },
  {
    title: 'Database Design with SQL',
    author: 'William Jackson',
    price: 70,
    category: 'development',
    image: '.\\images\\20.jpg',
  },
  {
    title: 'Email Marketing Automation',
    author: 'Mia White',
    price: 40,
    category: 'marketing',
    image: '.\\images\\21.jpg',
  },
  {
    title: 'Crisis Management in Business',
    author: 'Elijah Harris',
    price: 180,
    category: 'management',
    image: '.\\images\\22.jpg',
  },
  {
    title: 'Performance Review Best Practices',
    author: 'Harper Martin',
    price: 35,
    category: 'hr-recruiting',
    image: '.\\images\\23.jpg',
  },
  {
    title: 'Color Theory for Designers',
    author: 'Logan Thompson',
    price: 45,
    category: 'design',
    image: '.\\images\\24.jpg',
  },
  {
    title: 'Introduction to Cloud Computing',
    author: 'Amelia Garcia',
    price: 85,
    category: 'development',
    image: '.\\images\\25.jpg',
  },
  {
    title: 'PPC Advertising Basics',
    author: 'Benjamin Martinez',
    price: 50,
    category: 'marketing',
    image: '.\\images\\26.jpg',
  },
  {
    title: 'Strategic Planning Workshop',
    author: 'Evelyn Robinson',
    price: 75,
    category: 'management',
    image: '.\\images\\27.jpg',
  },
  {
    title: 'Recruitment Sourcing Strategies',
    author: 'Lucas Clark',
    price: 40,
    category: 'hr-recruiting',
    image: '.\\images\\28.jpg',
  },
  {
    title: 'UX Research Methods',
    author: 'Chloe Lewis',
    price: 60,
    category: 'design',
    image: '.\\images\\29.jpg',
  },
  {
    title: 'Front-End Development Libraries',
    author: 'Mason King',
    price: 90,
    category: 'development',
    image: '.\\images\\30.jpg',
  },
];
